#version 1
name: Test PR

on:
  pull_request

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: trilom/file-changes-action@v1.2.4
      id: file_changes    
